### ISSUE TITLE
fetch_symbols(): Reqwest Error: error decoding response body: unknown variant `Pending`

### ISSUE THREAD

**Issue by peepopoggers** [wassup-/bybit-rs#10]
When running this code:
```rust
//no problems with this part
let mut api = http::Client::new(
	http::MAINNET_BYBIT,
	bybit_pub_key,
	bybit_priv_key,
)
.unwrap();

//erroring part
println!("{:#?}", api.fetch_symbols().await?);
```

I get this error (no need for unwrap by my pr but this also is an error on your git repo):
```
Reqwest Error: error decoding response body: unknown variant `Pending`, expected one of `Trading`, `Settling`, `Closed` at line 1 column 45977 
```

**Comment by wassup-** [comment]
Hmm good catch! The [API docs](https://bybit-exchange.github.io/docs/inverse/#t-querysymbol) don't seem to mention the Pending [status](https://bybit-exchange.github.io/docs/inverse/#contract-status-status) anywhere.

I will add a `Pending` case to `ContractStatus`
